/*
 * @Author: your name
 * @Date: 2020-01-18 08:40:02
 * @LastEditTime : 2020-01-28 20:53:52
 * @LastEditors  : Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /music_app/js/redux/actionTypes/index.js
 */
export default {
  // 全局主题
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  // index
  BANNER_LOAD_SUCCESS: 'BANNER_SUCCESS',
  BANNER_LOAD_FAIL: 'BANNER_LOAD_FAIL',
  // personal
  LOGIN_LOAD_SUCCESS: 'LOGIN_LOAD_SUCCESS',
  LOGIN_LOAD_FAIL: 'LOGIN_LOAD_FAIL',
  GET_CODE_DATA_SUCCESS: 'GET_CODE_DATA_SUCCESS',
  GET_CODE_DATA_FAIL: 'GET_CODE_DATA_FAIL',
  //签到
  SIGNIN_LOAD_SUCCESS: 'SIGNIN_LOAD_SUCCESS',
  SIGNIN_LOAD_FAIL: 'SIGNIN_LOAD_FAIL',
  //电台
  RADIO_LOAD_SUCCESS: 'RADIO_LOAD_SUCCESS',
  RADIO_LOAD_FAIL: 'RADIO_LOAD_FAIL',
  // 排行榜
  TOP_LIST_LOAD_SUCCESS: 'TOP_LIST_LOAD_SUCCESS',
  TOP_LIST_LOAD_FAIL: 'TOP_LIST_LOAD_FAIL',
  // 歌单
  TOP_PlAY_HIGH_LOAD_SUCCESS: 'TOP_PlAY_HIGH_LOAD_SUCCESS',
  TOP_PlAY_HIGH_LOAD_FAIL: 'TOP_PlAY_HIGH_LOAD_FAIL',
  // 签到
  DAILY_SINGER_LOAD_SUCCESS: 'DAILY_SINGER_LOAD_SUCCESS',
  DAILY_SINGER_LOAD_FAIL: 'DAILY_SINGER_LOAD_FAIL',
}
